name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake SVG & GIF
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: ved-sharma-24y4
          outputs: ./dist

      - name: List output files
        run: ls -la dist

      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
